# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk11

#services:
#  - postgresql

#before_install:
#  - psql -c 'create database tracker;' -U postgres

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.ru.job4j.io/bash)

# Отправлять уведомление на почту shakasuone@gmail.com если сборка упала
notifications:
  email:
    recipients:
      shakasuone@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
#
env:
  global:
    - CODECOV_TOKEN="1b893e53-521d-463b-8191-c7f3fc7da7c1"